# Global configurations for Prometheus
global:
  scrape_interval: 15s  
  evaluation_interval: 15s 
  scrape_timeout: 10s     
  external_labels:
    monitor: 'cna-monitor'

# Scrape configurations for various targets
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape a Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrape Kubernetes components
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Scrape Kubernetes nodes for system-level metrics
  - job_name: 'kubernetes-nodes'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443

  # Scrape pods in Kubernetes
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_name]
        action: replace
        target_label: instance
        separator: '/'

  # Scrape services in Kubernetes
  - job_name: 'kubernetes-services'
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)

  # Scrape cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Scrape microservices running within the architecture
  - job_name: 'service-a'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        regex: service-a-(.*)
        action: replace
        target_label: instance
    metric_relabel_configs:
      - action: drop
        regex: '(service_a_metrics)'

  - job_name: 'service-b'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        regex: service-b-(.*)
        action: replace
        target_label: instance
    metric_relabel_configs:
      - action: drop
        regex: '(service_b_metrics)'

# Rule files for Prometheus alerts
rule_files:
  - '/prometheus/alert_rules.yml'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Remote write configuration for long-term storage
remote_write:
  - url: "https://remote-write-endpoint.website.com/api/v1/write"
    basic_auth:
      username: "write_user"
      password: "secure_password"

# Remote read configuration for long-term storage
remote_read:
  - url: "https://remote-read-endpoint.website.com/api/v1/read"
    basic_auth:
      username: "read_user"
      password: "secure_password"