name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies for Go
        run: |
          cd services/service-a
          go mod download

      - name: Build Go Microservice (Service A)
        run: |
          cd services/service-a
          go build -v ./...

      - name: Run Go Unit Tests (Service A)
        run: |
          cd services/service-a
          go test -v ./tests

      - name: Install Dependencies for Java
        run: |
          cd services/service-b
          ./mvnw install -DskipTests

      - name: Build Java Microservice (Service B)
        run: |
          cd services/service-b
          ./mvnw package

      - name: Run Java Unit Tests (Service B)
        run: |
          cd services/service-b
          ./mvnw test

      - name: Docker Build for Go Microservice
        run: |
          cd services/service-a
          docker build -t service-a .

      - name: Docker Build for Java Microservice
        run: |
          cd services/service-b
          docker build -t service-b .

      - name: Save Docker Images
        run: |
          docker save service-a service-b | gzip > services-images.tar.gz

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: service-images
          path: services-images.tar.gz