name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image for Service A
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t website.com/service-a:${{ github.sha }} \
          -f services/service-a/Dockerfile \
          --push .

    - name: Build and Push Docker Image for Service B
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t website.com/service-b:${{ github.sha }} \
          -f services/service-b/Dockerfile \
          --push .

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: "v1.22.0"

    - name: Deploy Service A to Kubernetes
      run: |
        kubectl apply -f services/service-a/deployment/k8s/deployment.yaml
        kubectl apply -f services/service-a/deployment/k8s/service.yaml

    - name: Deploy Service B to Kubernetes
      run: |
        kubectl apply -f services/service-b/deployment/k8s/deployment.yaml
        kubectl apply -f services/service-b/deployment/k8s/service.yaml

    - name: Verify Deployments
      run: |
        kubectl rollout status deployment/service-a-deployment
        kubectl rollout status deployment/service-b-deployment

    - name: Notify Deployment Success
      run: echo "Deployment Completed"