apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  labels:
    app: service-a
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a-container
        image: registry.website.com/service-a:latest  
        ports:
        - containerPort: 8080  
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: service-a-config
              key: environment
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: service-a-secrets
              key: database_url
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
      restartPolicy: Always